apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spring-petclinic-test
spec:
  project: default
  source:
    repoURL: 'https://github.com/xdevops-caj-lab-gitops/spring-petclinic-config.git'
    path: deploy/overlays/test
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: spring-petclinic-test
  syncPolicy:
    automated:
      selfHeal: true
